"""init

Revision ID: dc4d922da992
Revises:  None
Create Date: 2025-06-09 07:18:22.520653

"""

from typing import Sequence, Union

from alembic import op  # noqa F401
import sqlalchemy as sa  # noqa F401


# revision identifiers, used by Alembic.
revision: str = "dc4d922da992"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
